
export const dummyProducts = [
  
  {
    id: "1",
    name: "Smartphone Tecno Camon 20 premier 5G",
    description:
      "Smartphone canggih dengan kamera 108MP, baterai 5000mAh yang tahan lama, layar AMOLED 6.7 inch, dan prosesor terbaru untuk performa maksimal.",
    price: 4999000,
    image: "/img/Smartphone Tecno Camon 20 premier 5G.2.jpg",
    category: "elektronik",
    discount: 15,
    stock: 25,
    rating: 4.8,
    date: "2025-04-12",
  },
  {
    id: "2",
    name: "Laptop ASUS vivoBook 15",
    description:
      "Laptop tipis dan ringan dengan performa tinggi untuk produktivitas maksimal. Dilengkapi dengan prosesor Intel Core i7, RAM 16GB, dan SSD 512GB.",
    price: 12500000,
    image: "/img/laptop vivobook 15 2.jpeg",
    category: "elektronik",
    discount: 10,
    stock: 10,
    rating: 4.7,
    date: "2023-05-05",
  },
  {
    id: "3",
    name: "Smart TV 55 Inch 4K",
    description:
      "Smart TV dengan resolusi 4K, teknologi HDR, dan sistem operasi Android TV untuk pengalaman menonton yang lebih baik dan akses ke berbagai aplikasi streaming.",
    price: 7999000,
    image: "/img/Smart TV 55 Inch 4K.2.jpg",
    category: "elektronik",
    discount: 12,
    stock: 8,
    rating: 4.6,
    date: "2023-06-10",
  },
  {
    id: "4",
    name: "Headphone Bluetooth Premium",
    description:
      "Headphone bluetooth dengan kualitas suara premium, noise cancelling, dan baterai tahan lama hingga 30 jam penggunaan.",
    price: 1899000,
    image: "/img/Headphone Bluetooth Premium.2.jpg",
    category: "elektronik",
    discount: 15,
    stock: 18,
    rating: 4.7,
    date: "2023-07-15",
  },
  {
    id: "5",
    name: "Kamera Mirrorless",
    description:
      "Kamera mirrorless profesional dengan sensor full-frame 45MP, perekaman video 8K, dan sistem autofocus cepat untuk hasil foto dan video terbaik.",
    price: 24999000,
    image: "/img/Kamera Mirrorless.2.png",
    category: "elektronik",
    discount: 5,
    stock: 5,
    rating: 4.9,
    date: "2023-08-20",
  },
  {
    id: "6",
    name: "Smartwatch Fitness Tracker",
    description:
      "Smartwatch dengan fitur fitness tracker, monitor detak jantung, SpO2, GPS, dan tahan air hingga 50 meter untuk aktivitas sehari-hari dan olahraga.",
    price: 2499000,
    image: "/img/Smartwatch Fitness Tracker.2.png",
    category: "elektronik",
    discount: 20,
    stock: 15,
    rating: 4.5,
    date: "2023-09-10",
  },
  {
    id: "7",
    name: "Tablet Premium 10 Inch",
    description:
      "Tablet premium dengan layar 10 inch resolusi tinggi, prosesor cepat, dan baterai tahan lama untuk produktivitas dan hiburan.",
    price: 5999000,
    image: "/img/Tablet Premium 10 Inch.2.jpg",
    category: "elektronik",
    discount: 0,
    stock: 12,
    rating: 4.6,
    date: "2023-10-05",
  },
  {
    id: "8",
    name: "Speaker Bluetooth Portable",
    description:
      "Speaker bluetooth portable dengan suara jernih, bass yang kuat, tahan air, dan baterai tahan lama hingga 20 jam penggunaan.",
    price: 899000,
    image: "/img/Speaker Bluetooth Portable.2.jpg",
    category: "elektronik",
    discount: 0,
    stock: 30,
    rating: 4.4,
    date: "2023-11-15",
  },

  // Fashion Pria
  {
    id: "9",
    name: "Kemeja Formal Pria",
    description:
      "Kemeja formal pria dengan bahan premium dan nyaman dipakai sepanjang hari. Tersedia dalam berbagai ukuran dan warna.",
    price: 299000,
    image: "/img/Kemeja Formal Pria.2.png",
    category: "fashion-pria",
    discount: 0,
    stock: 50,
    rating: 4.5,
    date: "2023-05-10",
  },
  {
    id: "10",
    name: "Celana Jeans Pria",
    description:
      "Celana jeans pria dengan potongan slim fit dan bahan denim berkualitas tinggi. Nyaman dipakai dan tahan lama.",
    price: 399000,
    image: "/img/Celana Jeans Pria.2.png",
    category: "fashion-pria",
    discount: 0,
    stock: 45,
    rating: 4.5,
    date: "2023-06-15",
  },
  {
    id: "11",
    name: "Jaket Pria Waterproof",
    description:
      "Jaket pria waterproof untuk melindungi dari hujan dan angin dengan desain stylish. Cocok untuk aktivitas outdoor.",
    price: 599000,
    image: "/img/Jaket Pria Waterproof.2.png",
    category: "fashion-pria",
    discount: 10,
    stock: 25,
    rating: 4.6,
    date: "2023-07-20",
  },
  {
    id: "12",
    name: "Sepatu Sneakers Pria",
    description:
      "Sepatu sneakers pria dengan desain modern, sol empuk, dan nyaman dipakai sehari-hari. Tersedia dalam berbagai ukuran dan warna.",
    price: 799000,
    image: "/img/Sepatu Sneakers Pria.2.jpg",
    category: "fashion-pria",
    discount: 15,
    stock: 20,
    rating: 4.7,
    date: "2023-08-25",
  },
  {
    id: "13",
    name: "Kaos Polo Pria",
    description:
      "Kaos polo pria dengan bahan katun premium yang nyaman dan breathable. Cocok untuk casual dan semi-formal.",
    price: 199000,
    image: "/img/Kaos Polo Pria.2.png",
    category: "fashion-pria",
    discount: 0,
    stock: 60,
    rating: 4.4,
    date: "2023-09-15",
  },
  {
    id: "14",
    name: "Jam Tangan Pria Analog",
    description:
      "Jam tangan pria analog dengan desain elegan, tali stainless steel, dan water resistant hingga 50 meter.",
    price: 1299000,
    image: "/img/Jam Tangan Pria Analog.2.webp",
    category: "fashion-pria",
    discount: 10,
    stock: 15,
    rating: 4.8,
    date: "2023-10-10",
  },
  {
    id: "15",
    name: "Dompet Kulit Pria",
    description:
      "Dompet kulit asli pria dengan desain minimalis, banyak slot kartu, dan tahan lama. Cocok untuk hadiah.",
    price: 349000,
    image: "/img/Dompet Kulit Pria.2.webp",
    category: "fashion-pria",
    discount: 0,
    stock: 40,
    rating: 4.6,
    date: "2023-11-05",
  },
  {
    id: "16",
    name: "Topi Baseball Pria",
    description:
      "Topi baseball pria dengan bahan berkualitas, adjustable size, dan desain modern. Cocok untuk aktivitas outdoor.",
    price: 149000,
    image: "/img/Topi Baseball Pria.2.webp",
    category: "fashion-pria",
    discount: 0,
    stock: 70,
    rating: 4.3,
    date: "2023-12-01",
  },

  // Fashion Wanita
  {
    id: "17",
    name: "Dress Casual Wanita",
    description:
      "Dress casual wanita dengan desain modern dan bahan berkualitas tinggi. Nyaman dipakai untuk berbagai acara.",
    price: 359000,
    image: "/img/Dress Casual Wanita.2.jpg",
    category: "fashion-wanita",
    discount: 20,
    stock: 30,
    rating: 4.6,
    date: "2023-05-15",
  },
  {
    id: "18",
    name: "Tas Wanita Branded",
    description:
      "Tas wanita branded dengan desain elegan dan fungsional untuk kebutuhan sehari-hari. Terbuat dari bahan premium.",
    price: 1250000,
    image: "/img/Tas Wanita Branded.2.jpg",
    category: "fashion-wanita",
    discount: 25,
    stock: 12,
    rating: 4.8,
    date: "2023-06-20",
  },
  {
    id: "19",
    name: "Sepatu Wanita Casual",
    description:
      "Sepatu wanita casual dengan desain modern dan nyaman dipakai sehari-hari. Tersedia dalam berbagai ukuran dan warna.",
    price: 459000,
    image: "/img/Sepatu Wanita Casual.2.jpg",
    category: "fashion-wanita",
    discount: 10,
    stock: 22,
    rating: 4.5,
    date: "2023-07-25",
  },
  {
    id: "20",
    name: "Blouse Wanita Elegant",
    description:
      "Blouse wanita dengan desain elegant, bahan premium, dan nyaman dipakai. Cocok untuk acara formal dan semi-formal.",
    price: 279000,
    image: "/img/Blouse Wanita Elegant.2.jpeg",
    category: "fashion-wanita",
    discount: 0,
    stock: 35,
    rating: 4.7,
    date: "2023-08-30",
  },

  // Peralatan Rumah
  {
    id: "21",
    name: "Blender Multifungsi",
    description:
      "Blender multifungsi untuk membuat smoothie, jus, dan menghaluskan bahan makanan. Dengan motor kuat dan pisau tajam.",
    price: 799000,
    image: "/img/lender Multifungsi.2.webp",
    category: "peralatan-rumah",
    discount: 5,
    stock: 15,
    rating: 4.4,
    date: "2023-05-20",
  },
  {
    id: "22",
    name: "Rice Cooker Digital",
    description:
      "Rice cooker digital dengan berbagai fitur canggih untuk memasak nasi yang sempurna. Dilengkapi dengan timer dan keep warm.",
    price: 599000,
    image: "/img/Rice Cooker Digital.2.jpeg",
    category: "peralatan-rumah",
    discount: 8,
    stock: 20,
    rating: 4.7,
    date: "2023-06-25",
  },

  // Makanan & Minuman
  {
    id: "23",
    name: "Snack Box Premium",
    description: "Paket snack premium dengan berbagai macam camilan lezat dan bergizi. Cocok untuk acara dan hadiah.",
    price: 150000,
    image: "/img/Snack Box Premium.2.jpeg",
    category: "makanan-minuman",
    discount: 0,
    stock: 100,
    rating: 4.3,
    date: "2023-05-25",
  },
  {
    id: "24",
    name: "Kopi Premium 250g",
    description:
      "Kopi premium dengan aroma dan rasa yang kaya, cocok untuk pecinta kopi sejati. Single origin dari perkebunan terbaik.",
    price: 120000,
    image: "/img/Kopi Premium 250g.2.jpeg",
    category: "makanan-minuman",
    discount: 0,
    stock: 80,
    rating: 4.9,
    date: "2023-07-01",
  },

  // Kesehatan
  {
    id: "25",
    name: "Vitamin C 1000mg",
    description:
      "Suplemen vitamin C dosis tinggi untuk meningkatkan daya tahan tubuh. Konsumsi rutin untuk hasil optimal.",
    price: 85000,
    image: "/img/Vitamin C 1000mg.2.jpeg",
    category: "kesehatan",
    discount: 0,
    stock: 200,
    rating: 4.9,
    date: "2023-06-01",
  },
  {
    id: "26",
    name: "Masker Wajah Organik",
    description:
      "Masker wajah dengan bahan organik untuk merawat kulit wajah secara alami. Cocok untuk semua jenis kulit.",
    price: 75000,
    image: "/img/Masker Wajah Organik.2.jpeg",
    category: "kesehatan",
    discount: 10,
    stock: 150,
    rating: 4.6,
    date: "2023-07-05",
  },

  // Buku & Alat Tulis
  {
    id: "27",
    name: "Novel Bestseller",
    description:
      "Novel bestseller karya penulis terkenal dengan cerita yang menarik dan menginspirasi. Edisi terbaru dengan sampul keras.",
    price: 125000,
    image: "/img/Novel Bestseller.2.jpeg",
    category: "buku-alat-tulis",
    discount: 0,
    stock: 40,
    rating: 4.7,
    date: "2023-06-05",
  },
  {
    id: "28",
    name: "Set Alat Tulis Lengkap",
    description:
      "Set alat tulis lengkap dengan berbagai perlengkapan untuk kebutuhan sekolah dan kantor. Kualitas premium.",
    price: 199000,
    image: "/img/Set Alat Tulis Lengkap.2.jpeg",
    category: "buku-alat-tulis",
    discount: 5,
    stock: 35,
    rating: 4.5,
    date: "2023-07-10",
  },
]
